ALTER TABLE pets DROP CONSTRAINT IF EXISTS fk_pets_health;
ALTER TABLE pets DROP COLUMN IF EXISTS health_id;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS vaccinated BOOLEAN;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS sterilized BOOLEAN;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS diseases VARCHAR(255);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS health_service_id BIGINT;
DROP TABLE IF EXISTS pet_health;
