ALTER TABLE pets DROP COLUMN IF EXISTS vaccinated;
ALTER TABLE pets DROP COLUMN IF EXISTS sterilized;
ALTER TABLE pets DROP COLUMN IF EXISTS diseases;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
